In [11]:
import pandas as pd

products = [
    pd.read_csv("filluminate_products_001.csv"),
    pd.read_csv("filluminate_products_002.csv"),
    pd.read_csv("filluminate_products_003.csv"),
    pd.read_csv("travel_products_001.csv"),
    pd.read_csv("travel_products_002.csv"),
    pd.read_csv("travel_products_003.csv"),
    pd.read_csv("jemut_products_001.csv"),
    pd.read_csv("jemut_products_002.csv"),
    pd.read_csv("jemut_products_003.csv")
]

reviews = [
    pd.read_csv("filluminate_reviews_001.csv"),
    pd.read_csv("filluminate_reviews_002.csv"),
    pd.read_csv("filluminate_reviews_003.csv"),
    pd.read_csv("travel_reviews_001.csv"),
    pd.read_csv("travel_reviews_002.csv"),
    pd.read_csv("travel_reviews_003.csv"),
    pd.read_csv("jemut_reviews_001.csv"),
    pd.read_csv("jemut_reviews_002.csv"),
    pd.read_csv("jemut_reviews_003.csv")
]

products_all = pd.concat(products, ignore_index=True)
reviews_all = pd.concat(reviews, ignore_index=True)

# 결과 확인
print(f"Products shape: {products_all.shape}")
print(f"Reviews shape: {reviews_all.shape}")

Products shape: (1541, 12)
Reviews shape: (549727, 14)

In [15]:
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:msoo5880@localhost/review_analysis?charset=utf8mb4')

df_pd_rv_all = pd.read_sql("SELECT * FROM products_reviews_all", engine)
df_pd_rv_all['리뷰번호'].isnull().sum()

np.int64(294)

In [19]:
reviews_all.head()

,goodsNo,리뷰번호,작성자,리뷰내용,평점,체험단,구매옵션,키,몸무게,성별,작성일,만족도,사진유무,도움돼요
0,994588,83653892,I’m the one,고민많이했는데 역시 구매하니깐 만족이네요 추천합니다,5,False,M(옥스포드),173,70,남성,2026-04-13T19:36:44.000+09:00,사이즈: 정사이즈 / 화면 대비 색감: 화면과 비슷 / 퀄리티: 보통 / 구김: 약...,False,0
1,994588,83634873,배요,처음 배송 받고 노란색 실이 같이 박음질 되어 있어서 교환 한 번 받았습니다 주문 ...,5,False,S(린넨),178,63,남성,2026-04-12T22:19:25.000+09:00,사이즈: 조금 큼 / 화면 대비 색감: 화면과 비슷 / 퀄리티: 보통 / 구김: 약...,True,1
2,994588,83633528,근면한서울키링,구김도 덜 생기고 톡톡하니 예뻐요 린넨 옥스포드 각각 한개 삼 !,5,False,S(옥스포드),160,67,여성,2026-04-12T21:35:14.000+09:00,사이즈: 조금 큼 / 화면 대비 색감: 화면과 비슷 / 퀄리티: 좋음 / 구김: 약...,True,0
3,994588,83633476,근면한서울키링,휘뚜루 마뚜루 잘 입어지고 구김도 잘 가요~ 사이즈는 s인데도 커요~^^,5,False,S(린넨),160,67,여성,2026-04-12T21:33:55.000+09:00,사이즈: 조금 큼 / 화면 대비 색감: 화면과 비슷 / 퀄리티: 좋음 / 구김: 많음,True,0
4,994588,83618492,세일중인발리바지,오버핏으로 한치수 크게 구매했는데 따맞아서 좋아여,5,False,L(린넨),174,68,남성,2026-04-12T08:36:31.000+09:00,사이즈: 정사이즈 / 화면 대비 색감: 화면과 비슷 / 퀄리티: 매우 좋음 / 구김...,False,0

In [27]:
outer = reviews_all[reviews_all['goodsNo'] == 1291017]

In [28]:
outer['작성자'].value_counts()

작성자
-           93
황곰잉         11
유기농똥강아지      7
더치아이스        7
린 쟈오밍        6
            ..
psch23       1
맑은두바이클래식     1
단정한강남숄더백     1
안락한대학로패션     1
시원한터키모헤어     1
Name: count, Length: 11976, dtype: int64

In [30]:
outer[outer['작성자']=='황곰잉']

,goodsNo,리뷰번호,작성자,리뷰내용,평점,체험단,구매옵션,키,몸무게,성별,작성일,만족도,사진유무,도움돼요
447636,1291017,67512369,황곰잉,좀 얇은게 흠인데 가을동안 잘 입었어요 편하게 입기 좋아요,5,False,블랙 · M,163,50,여성,2024-11-26T08:12:28.000+09:00,NaN,True,0
447842,1291017,65593657,황곰잉,몇년전 구매해서 잘입었는데 해져가지고 재구매 했어요 \n,5,False,블랙 · M,163,50,여성,2024-10-15T15:50:19.000+09:00,NaN,True,0
451420,1291017,40225963,황곰잉,여자가 입기엔 약간 큰듯하나 크게 입으려고 산거여서 전 딱 좋네요 보통 여자옷 55입어요,5,False,블랙 · M,163,48,여성,2023-03-07T18:45:08.000+09:00,NaN,True,0
451421,1291017,40225902,황곰잉,남편꺼랑 같이 샀는데 입기 편하고 막입어도 좋아요\n,5,False,블랙 · XL,178,90,남성,2023-03-07T18:43:58.000+09:00,NaN,True,0
451509,1291017,40079342,황곰잉,남편이랑 같은거 사서 잘입었어요\n보통 55에 S사이즈 입는데 약간커요,5,False,블랙 · M,163,48,여성,2023-03-04T13:22:38.000+09:00,NaN,True,1
451510,1291017,40079239,황곰잉,여행가서 잘입었어요\n보통 105입고 사이즈 잘 맞아요,5,False,블랙 · XL,178,90,남성,2023-03-04T13:19:58.000+09:00,NaN,True,0
451957,1291017,39293232,황곰잉,갖고 있던건데 많이 입어서 해져가지고 재구매 했어요\n오버핏으로 입기 좋아요\n,5,False,블랙 · M,163,48,여성,2023-02-14T18:28:43.000+09:00,NaN,False,0
451958,1291017,39293183,황곰잉,사이즈도 정사이즈 잘맞고 핏도 이쁘게 떨어져요\n아직은 추워서 못입지만 미리 구매 했어요,5,False,블랙 · XL,178,90,남성,2023-02-14T18:27:31.000+09:00,NaN,False,0
458694,1291017,16441319,황곰잉,보통 55사이즈 입는데 M사이즈 잘 맞아요 \n두께가 있어서 이젠 못입는게 좀 아쉽...,5,False,블랙 · M,163,45,여성,2021-04-26T22:53:54.000+09:00,NaN,True,0
459185,1291017,15860786,황곰잉,집에있던 항공점퍼가 넘 헤져서 구매했는데\n좀 큰감이 있지만 크게 입으려고 산거라 ...,5,False,블랙 · M,163,45,여성,2021-03-29T11:26:50.000+09:00,NaN,False,0
459188,1291017,15854256,황곰잉,좀 크긴한데 크게 입을려고 구매한거라 좋아요\n두께감도 지금 딱이에요,5,False,블랙 · M,163,45,여성,2021-03-28T22:40:27.000+09:00,NaN,True,3