In [11]:
import pandas as pd

products = [
    pd.read_csv("filluminate_products_001.csv"),
    pd.read_csv("filluminate_products_002.csv"),
    pd.read_csv("filluminate_products_003.csv"),
    pd.read_csv("travel_products_001.csv"),
    pd.read_csv("travel_products_002.csv"),
    pd.read_csv("travel_products_003.csv"),
    pd.read_csv("jemut_products_001.csv"),
    pd.read_csv("jemut_products_002.csv"),
    pd.read_csv("jemut_products_003.csv")
]

reviews = [
    pd.read_csv("filluminate_reviews_001.csv"),
    pd.read_csv("filluminate_reviews_002.csv"),
    pd.read_csv("filluminate_reviews_003.csv"),
    pd.read_csv("travel_reviews_001.csv"),
    pd.read_csv("travel_reviews_002.csv"),
    pd.read_csv("travel_reviews_003.csv"),
    pd.read_csv("jemut_reviews_001.csv"),
    pd.read_csv("jemut_reviews_002.csv"),
    pd.read_csv("jemut_reviews_003.csv")
]

products_all = pd.concat(products, ignore_index=True)
reviews_all = pd.concat(reviews, ignore_index=True)

# 결과 확인
print(f"Products shape: {products_all.shape}")
print(f"Reviews shape: {reviews_all.shape}")

Products shape: (1541, 12)
Reviews shape: (549727, 14)

In [15]:
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:msoo5880@localhost/review_analysis?charset=utf8mb4')

df_pd_rv_all = pd.read_sql("SELECT * FROM products_reviews_all", engine)
df_pd_rv_all['리뷰번호'].isnull().sum()

np.int64(294)

In [19]:
reviews_all.head()

,goodsNo,리뷰번호,작성자,리뷰내용,평점,체험단,구매옵션,키,몸무게,성별,작성일,만족도,사진유무,도움돼요
0,994588,83653892,I’m the one,고민많이했는데 역시 구매하니깐 만족이네요 추천합니다,5,False,M(옥스포드),173,70,남성,2026-04-13T19:36:44.000+09:00,사이즈: 정사이즈 / 화면 대비 색감: 화면과 비슷 / 퀄리티: 보통 / 구김: 약...,False,0
1,994588,83634873,배요,처음 배송 받고 노란색 실이 같이 박음질 되어 있어서 교환 한 번 받았습니다 주문 ...,5,False,S(린넨),178,63,남성,2026-04-12T22:19:25.000+09:00,사이즈: 조금 큼 / 화면 대비 색감: 화면과 비슷 / 퀄리티: 보통 / 구김: 약...,True,1
2,994588,83633528,근면한서울키링,구김도 덜 생기고 톡톡하니 예뻐요 린넨 옥스포드 각각 한개 삼 !,5,False,S(옥스포드),160,67,여성,2026-04-12T21:35:14.000+09:00,사이즈: 조금 큼 / 화면 대비 색감: 화면과 비슷 / 퀄리티: 좋음 / 구김: 약...,True,0
3,994588,83633476,근면한서울키링,휘뚜루 마뚜루 잘 입어지고 구김도 잘 가요~ 사이즈는 s인데도 커요~^^,5,False,S(린넨),160,67,여성,2026-04-12T21:33:55.000+09:00,사이즈: 조금 큼 / 화면 대비 색감: 화면과 비슷 / 퀄리티: 좋음 / 구김: 많음,True,0
4,994588,83618492,세일중인발리바지,오버핏으로 한치수 크게 구매했는데 따맞아서 좋아여,5,False,L(린넨),174,68,남성,2026-04-12T08:36:31.000+09:00,사이즈: 정사이즈 / 화면 대비 색감: 화면과 비슷 / 퀄리티: 매우 좋음 / 구김...,False,0

In [27]:
outer = reviews_all[reviews_all['goodsNo'] == 1291017]

In [28]:
outer['작성자'].value_counts()

작성자
-           93
황곰잉         11
유기농똥강아지      7
더치아이스        7
린 쟈오밍        6
            ..
psch23       1
맑은두바이클래식     1
단정한강남숄더백     1
안락한대학로패션     1
시원한터키모헤어     1
Name: count, Length: 11976, dtype: int64

In [30]:
outer[outer['작성자']=='황곰잉']

,goodsNo,리뷰번호,작성자,리뷰내용,평점,체험단,구매옵션,키,몸무게,성별,작성일,만족도,사진유무,도움돼요
447636,1291017,67512369,황곰잉,좀 얇은게 흠인데 가을동안 잘 입었어요 편하게 입기 좋아요,5,False,블랙 · M,163,50,여성,2024-11-26T08:12:28.000+09:00,NaN,True,0
447842,1291017,65593657,황곰잉,몇년전 구매해서 잘입었는데 해져가지고 재구매 했어요 \n,5,False,블랙 · M,163,50,여성,2024-10-15T15:50:19.000+09:00,NaN,True,0
451420,1291017,40225963,황곰잉,여자가 입기엔 약간 큰듯하나 크게 입으려고 산거여서 전 딱 좋네요 보통 여자옷 55입어요,5,False,블랙 · M,163,48,여성,2023-03-07T18:45:08.000+09:00,NaN,True,0
451421,1291017,40225902,황곰잉,남편꺼랑 같이 샀는데 입기 편하고 막입어도 좋아요\n,5,False,블랙 · XL,178,90,남성,2023-03-07T18:43:58.000+09:00,NaN,True,0
451509,1291017,40079342,황곰잉,남편이랑 같은거 사서 잘입었어요\n보통 55에 S사이즈 입는데 약간커요,5,False,블랙 · M,163,48,여성,2023-03-04T13:22:38.000+09:00,NaN,True,1
451510,1291017,40079239,황곰잉,여행가서 잘입었어요\n보통 105입고 사이즈 잘 맞아요,5,False,블랙 · XL,178,90,남성,2023-03-04T13:19:58.000+09:00,NaN,True,0
451957,1291017,39293232,황곰잉,갖고 있던건데 많이 입어서 해져가지고 재구매 했어요\n오버핏으로 입기 좋아요\n,5,False,블랙 · M,163,48,여성,2023-02-14T18:28:43.000+09:00,NaN,False,0
451958,1291017,39293183,황곰잉,사이즈도 정사이즈 잘맞고 핏도 이쁘게 떨어져요\n아직은 추워서 못입지만 미리 구매 했어요,5,False,블랙 · XL,178,90,남성,2023-02-14T18:27:31.000+09:00,NaN,False,0
458694,1291017,16441319,황곰잉,보통 55사이즈 입는데 M사이즈 잘 맞아요 \n두께가 있어서 이젠 못입는게 좀 아쉽...,5,False,블랙 · M,163,45,여성,2021-04-26T22:53:54.000+09:00,NaN,True,0
459185,1291017,15860786,황곰잉,집에있던 항공점퍼가 넘 헤져서 구매했는데\n좀 큰감이 있지만 크게 입으려고 산거라 ...,5,False,블랙 · M,163,45,여성,2021-03-29T11:26:50.000+09:00,NaN,False,0
459188,1291017,15854256,황곰잉,좀 크긴한데 크게 입을려고 구매한거라 좋아요\n두께감도 지금 딱이에요,5,False,블랙 · M,163,45,여성,2021-03-28T22:40:27.000+09:00,NaN,True,3

In [1]:
import pandas as pd

products = [
    pd.read_csv("filluminate_products_001.csv"),
    pd.read_csv("filluminate_products_002.csv"),
    pd.read_csv("filluminate_products_003.csv"),
    pd.read_csv("travel_products_001.csv"),
    pd.read_csv("travel_products_002.csv"),
    pd.read_csv("travel_products_003.csv"),
    pd.read_csv("jemut_products_001.csv"),
    pd.read_csv("jemut_products_002.csv"),
    #pd.read_csv("jemut_products_003.csv")
]

reviews = [
    pd.read_csv("filluminate_reviews_001.csv"),
    pd.read_csv("filluminate_reviews_002.csv"),
    pd.read_csv("filluminate_reviews_003.csv"),
    pd.read_csv("travel_reviews_001.csv"),
    pd.read_csv("travel_reviews_002.csv"),
    pd.read_csv("travel_reviews_003.csv"),
    pd.read_csv("jemut_reviews_001.csv"),
    pd.read_csv("jemut_reviews_002.csv"),
    #pd.read_csv("jemut_reviews_003.csv")
]

products_all = pd.concat(products, ignore_index=True)
reviews_all = pd.concat(reviews, ignore_index=True)

# 결과 확인
print(f"Products shape: {products_all.shape}")
print(f"Reviews shape: {reviews_all.shape}")

Products shape: (1276, 12)
Reviews shape: (492504, 15)

In [2]:
reviews_all.head()

,goodsNo,리뷰번호,리뷰타입,작성자,리뷰내용,평점,체험단,구매옵션,키,몸무게,성별,작성일,만족도,사진유무,도움돼요
0,994588,83869615,general,서서서세,셔츠가 잘 나와서 예쁩니다 만족합니다 강력추천,5,False,L(린넨),175,93,남성,2026-04-22T07:58:11.000+09:00,사이즈: 정사이즈 / 화면 대비 색감: 밝음 / 퀄리티: 좋음 / 구김: 약간 있음,False,0
1,994588,83839787,general,착한빨강플리스,"배송이 좀 느렸지만, 옷은 좋아요 오버핏이라 외투로 입어도 될듯",5,False,S(린넨),176,60,남성,2026-04-21T01:34:03.000+09:00,사이즈: 정사이즈 / 화면 대비 색감: 화면과 비슷 / 퀄리티: 매우 좋음 / 구김...,True,0
2,994588,83801548,general,Hw_0317,전체적으로 오버핏에 옷이 짱짱하고 넘 이뻐요. 가성비도 좋고요.,5,False,M(옥스포드),170,66,남성,2026-04-19T16:42:22.000+09:00,사이즈: 조금 큼 / 화면 대비 색감: 화면과 비슷 / 퀄리티: 보통 / 구김: 거...,False,0
3,994588,83801354,general,은밀한유럽라펠,두께감 약간 있고 구김 안생깁니다. 자주 입고 다닐 것 같아요,5,False,L(옥스포드),180,60,남성,2026-04-19T16:32:54.000+09:00,사이즈: 정사이즈 / 화면 대비 색감: 화면과 비슷 / 퀄리티: 좋음 / 구김: 거...,True,0
4,994588,83801288,general,은밀한유럽라펠,구김 잘 안생기고 예쁜 셔츠입니다. 잘 입고 다닐것 같아요,5,False,L(린넨),180,60,남성,2026-04-19T16:29:29.000+09:00,사이즈: 정사이즈 / 화면 대비 색감: 화면과 비슷 / 퀄리티: 좋음 / 구김: 거...,True,0

In [3]:
reviews_all['리뷰타입'].value_counts()

리뷰타입
goods         258177
style          75075
photo          74340
general        62100
month          22394
experience       418
Name: count, dtype: int64

In [4]:
reviews_all[reviews_all['리뷰타입'] == 'goods']

,goodsNo,리뷰번호,리뷰타입,작성자,리뷰내용,평점,체험단,구매옵션,키,몸무게,성별,작성일,만족도,사진유무,도움돼요
3129,994588,63953974,goods,능숙한스위스스틸,저렴한 가격에 넉넉한 디자인 편안하게 잘 입을께요 빠른배송 감사해요,5,False,M(옥스포드),162,60,여성,2024-08-19T01:04:31.000+09:00,NaN,False,0
3132,994588,63953862,goods,능숙한스위스스틸,사이즈가 넉넉해서 편하게 입을수 있어요 빠른배송 감사해요,5,False,M(린넨),162,60,여성,2024-08-19T00:22:08.000+09:00,NaN,False,0
3133,994588,63948084,goods,부산사람입니당,여자친구랑 데이트하면서 잘 입을 수 있는 무난한 셔츠라고 생각됩니다 생각보다 많이 ...,5,False,M(옥스포드),175,60,남성,2024-08-18T23:41:14.000+09:00,NaN,False,0
3135,994588,63907028,goods,맛있는밤,길줄알앗는데 키183 이면 딱 조은세미오버핏으로 떨어지네요,5,False,L(린넨),183,78,남성,2024-08-18T13:44:39.000+09:00,NaN,False,0
3137,994588,63902009,goods,캉캉우동,좋습니다 큰 느낌으로 입을 수 있어서 좋도 열고 입으면 좋아요,5,False,M(옥스포드),170,65,남성,2024-08-18T11:39:31.000+09:00,NaN,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492383,3516252,53390304,goods,코코157,적당한 두께감입니다 색깔은 초록색 갈색 회색 적당히 섞인 느낌이에요,5,False,다크모카 · M,176,63,남성,2023-12-19T20:15:44.000+09:00,NaN,False,0
492386,3516252,53286779,goods,아빠토끼,편하게 입기 좋아요 어떤 옷에든 무난하게 매칭가능,4,False,다크모카 · XL,176,82,남성,2023-12-17T15:44:28.000+09:00,NaN,False,0
492387,3516252,50130618,goods,고구마구만,와 진짜 무겁습니다 글을 제대로 안보고 산 제 탓이긴 한데 옷이 무거워봐야 얼마나 ...,3,False,다크모카 · L,166,52,여성,2023-10-24T13:24:54.000+09:00,NaN,False,0
492491,3593969,52165294,goods,기무영웅,너무 튼튼해요 아주빠르고여 보라색 좋아하시면 완추!,5,False,퍼플 · XL,0,0,NaN,2023-11-30T09:54:37.000+09:00,NaN,False,0
492495,3516254,51158013,goods,my-name-is-sky,잠바가 오버핏이라 편하게 입기 좋아요 활동하기 편하고요.,4,False,틸블루 · 2XL,175,90,남성,2023-11-15T16:52:26.000+09:00,NaN,False,0

In [11]:
reviews_all[(reviews_all['goodsNo']==994588) & (reviews_all['리뷰타입']=='month')]

,goodsNo,리뷰번호,리뷰타입,작성자,리뷰내용,평점,체험단,구매옵션,키,몸무게,성별,작성일,만족도,사진유무,도움돼요
705,994588,77648709,month,Azul de Corea,와우 좋은 셔츠 예뻐요 오버핏인데 사람이 커보임,5,False,S(린넨),172,61,남성,2025-08-15T09:22:55.000+09:00,NaN,False,0
715,994588,77461636,month,미묘한이태원더비,아주 아주 아주 맘에 드네요 제가 조아하는 스타일이랑 비슷해서 좋아요,5,False,L(옥스포드),173,74,남성,2025-08-06T22:38:47.000+09:00,NaN,False,0
718,994588,77361450,month,혼밥중인파랑실크,"안에 컬러감 있는 옷 입으면 비쳐요 맨살은 그렇게 비치진 않는 것 같고, 재질과 기...",5,False,M(린넨),177,57,남성,2025-08-03T03:29:07.000+09:00,NaN,False,0
721,994588,77306357,month,이불불나,이가격에 이셔츠 가성비가 너무 좋습니다 린넨이라 덥지도않고 여름에 좋아요,5,False,M(린넨),172,64,남성,2025-08-01T00:13:09.000+09:00,NaN,False,0
723,994588,77270204,month,랩이좋은홍콩레더,색감도 이쁘고 사이즈도 너무 마음에 들어요 많이 파세여,5,False,M(린넨),173,65,남성,2025-07-30T19:44:03.000+09:00,NaN,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3121,994588,63996884,month,핑크하마,기장이 생각한거보다 살짝 짧긴하지만 품도 넓고 잘 입을거 같아요,5,False,L(옥스포드),182,95,남성,2024-08-20T18:37:08.000+09:00,NaN,False,0
3123,994588,63992724,month,창조적인광주스판,박시한 와이셔츠 필요해서 샀어요 ~ 핏도 넉넉하고 정사이즈네요 ~~,5,False,L(옥스포드),160,47,여성,2024-08-20T15:54:07.000+09:00,NaN,True,0
3124,994588,63990530,month,환상적인강남마켓,진짜 너무 핏 이쁩니다 기장은 좀 큽니다 재질이 매우 좋습니다,5,False,L(린넨),174,65,남성,2024-08-20T14:26:52.000+09:00,NaN,False,0
3125,994588,63978291,month,으아너무비싸,시원하고 가벼워서 입기좋고 벗고 들고다녀도 무겁지않아서 좋아요,5,False,M(린넨),170,58,남성,2024-08-19T22:22:42.000+09:00,NaN,False,0
3128,994588,63967279,month,장마엔니스코튼,좀 두꺼워서 덥긴 했는데 너무 예뻐요 비침 없어서 셔츠만 입어도 됩니다,5,False,L(린넨),181,76,남성,2024-08-19T14:43:47.000+09:00,NaN,False,0

In [ ]:
display(reviews_all[reviews_all['리뷰번호'] == 61731480])
# filluminate_reviews_001 61721157,61731480

,goodsNo,리뷰번호,리뷰타입,작성자,리뷰내용,평점,체험단,구매옵션,키,몸무게,성별,작성일,만족도,사진유무,도움돼요
38740,3791891,61731480,goods,불_한_당,얇을줄알았는데 생각보다 두꺼웠어용 그래도 옷이 예쁘긴합니당,4,False,M,172,60,남성,2024-07-02T01:06:27.000+09:00,NaN,False,0
38741,3791891,61731480,goods,불_한_당,얇을줄알았는데 생각보다 두꺼웠어용 그래도 옷이 예쁘긴합니당,4,False,M,172,60,남성,2024-07-02T01:06:27.000+09:00,NaN,False,0

In [16]:
display(reviews_all[reviews_all['리뷰번호'] == 76491276])

,goodsNo,리뷰번호,리뷰타입,작성자,리뷰내용,평점,체험단,구매옵션,키,몸무게,성별,작성일,만족도,사진유무,도움돼요
30000,3791891,76491276,general,라이보우,여름에 입기에는 더울수가있어서 낮에는 못입고 밤에는 접어서 입어야 할꺼 같아요 생각...,5,False,L,177,75,남성,2025-07-05T06:55:12.000+09:00,NaN,False,0

In [15]:
display(reviews_all[reviews_all['리뷰번호'] == 69640489])

,goodsNo,리뷰번호,리뷰타입,작성자,리뷰내용,평점,체험단,구매옵션,키,몸무게,성별,작성일,만족도,사진유무,도움돼요
110329,3791988,69640489,general,놀라운광저우단추,키 168인데요 바지 길이는 바닥에서 살짝 뜹니다 조금 더 길었으면 좋았을 것 같고...,5,False,S,168,56,여성,2025-01-05T12:19:21.000+09:00,NaN,True,0
115878,3791988,69640489,general,놀라운광저우단추,키 168인데요 바지 길이는 바닥에서 살짝 뜹니다 조금 더 길었으면 좋았을 것 같고...,5,False,S,168,56,여성,2025-01-05T12:19:21.000+09:00,NaN,True,0
115879,3791988,69640489,general,놀라운광저우단추,키 168인데요 바지 길이는 바닥에서 살짝 뜹니다 조금 더 길었으면 좋았을 것 같고...,5,False,S,168,56,여성,2025-01-05T12:19:21.000+09:00,NaN,True,0

In [18]:
display(reviews_all[reviews_all['리뷰번호'] == 64100853])

,goodsNo,리뷰번호,리뷰타입,작성자,리뷰내용,평점,체험단,구매옵션,키,몸무게,성별,작성일,만족도,사진유무,도움돼요
113958,3791988,64100853,general,내일은회색클래식,완전 이쁘고 사이즈도 잘 맞고 색상도 트랜디해서 좋아요,5,False,M,150,37,여성,2024-08-24T22:13:46.000+09:00,NaN,False,0

In [21]:
reviews_all[reviews_all.duplicated(keep=False)]

,goodsNo,리뷰번호,리뷰타입,작성자,리뷰내용,평점,체험단,구매옵션,키,몸무게,성별,작성일,만족도,사진유무,도움돼요
38740,3791891,61731480,goods,불_한_당,얇을줄알았는데 생각보다 두꺼웠어용 그래도 옷이 예쁘긴합니당,4,False,M,172,60,남성,2024-07-02T01:06:27.000+09:00,NaN,False,0
38741,3791891,61731480,goods,불_한_당,얇을줄알았는데 생각보다 두꺼웠어용 그래도 옷이 예쁘긴합니당,4,False,M,172,60,남성,2024-07-02T01:06:27.000+09:00,NaN,False,0
38750,3791891,61721157,goods,톨랭방구,진빠 예뻐요 꼳사세요 고민하믄시간이 아까워요,5,False,M,157,65,여성,2024-07-01T22:38:12.000+09:00,NaN,False,0
38751,3791891,61721157,goods,톨랭방구,진빠 예뻐요 꼳사세요 고민하믄시간이 아까워요,5,False,M,157,65,여성,2024-07-01T22:38:12.000+09:00,NaN,False,0
110329,3791988,69640489,general,놀라운광저우단추,키 168인데요 바지 길이는 바닥에서 살짝 뜹니다 조금 더 길었으면 좋았을 것 같고...,5,False,S,168,56,여성,2025-01-05T12:19:21.000+09:00,NaN,True,0
110330,3791988,69639664,month,와칰,내가 원하는 핏이었어서 마음에 들어요 바지통이 제가ㅜ입어봤던거중에 제일 커요,5,False,S,169,70,남성,2025-01-05T11:48:32.000+09:00,NaN,False,0
110331,3791988,69634907,general,로냐뉴,바비 전체적인 색감이랑 워싱도 너무 이쁘고 핏도 좋아요,5,False,M,174,69,남성,2025-01-05T03:22:11.000+09:00,NaN,True,0
110332,3791988,69633758,general,으으응호오오,핏이며 색상이며 너무 이쁘네요 사진보다 약간 더 진한느낌이있어요,5,False,M,174,70,남성,2025-01-05T01:45:06.000+09:00,NaN,False,0
110333,3791988,69632874,month,은은한덕수궁샌들,여행가서 잘입었어용 근데 많이 걸으니까 천에 쓸려서 살 다까짐 ㅠㅜ,4,False,S,166,60,여성,2025-01-05T01:07:47.000+09:00,NaN,True,0
115878,3791988,69640489,general,놀라운광저우단추,키 168인데요 바지 길이는 바닥에서 살짝 뜹니다 조금 더 길었으면 좋았을 것 같고...,5,False,S,168,56,여성,2025-01-05T12:19:21.000+09:00,NaN,True,0
115879,3791988,69640489,general,놀라운광저우단추,키 168인데요 바지 길이는 바닥에서 살짝 뜹니다 조금 더 길었으면 좋았을 것 같고...,5,False,S,168,56,여성,2025-01-05T12:19:21.000+09:00,NaN,True,0
115880,3791988,69639664,month,와칰,내가 원하는 핏이었어서 마음에 들어요 바지통이 제가ㅜ입어봤던거중에 제일 커요,5,False,S,169,70,남성,2025-01-05T11:48:32.000+09:00,NaN,False,0
115881,3791988,69639664,month,와칰,내가 원하는 핏이었어서 마음에 들어요 바지통이 제가ㅜ입어봤던거중에 제일 커요,5,False,S,169,70,남성,2025-01-05T11:48:32.000+09:00,NaN,False,0
115882,3791988,69634907,general,로냐뉴,바비 전체적인 색감이랑 워싱도 너무 이쁘고 핏도 좋아요,5,False,M,174,69,남성,2025-01-05T03:22:11.000+09:00,NaN,True,0
115883,3791988,69634907,general,로냐뉴,바비 전체적인 색감이랑 워싱도 너무 이쁘고 핏도 좋아요,5,False,M,174,69,남성,2025-01-05T03:22:11.000+09:00,NaN,True,0
115884,3791988,69633758,general,으으응호오오,핏이며 색상이며 너무 이쁘네요 사진보다 약간 더 진한느낌이있어요,5,False,M,174,70,남성,2025-01-05T01:45:06.000+09:00,NaN,False,0
115885,3791988,69633758,general,으으응호오오,핏이며 색상이며 너무 이쁘네요 사진보다 약간 더 진한느낌이있어요,5,False,M,174,70,남성,2025-01-05T01:45:06.000+09:00,NaN,False,0
115886,3791988,69632874,month,은은한덕수궁샌들,여행가서 잘입었어용 근데 많이 걸으니까 천에 쓸려서 살 다까짐 ㅠㅜ,4,False,S,166,60,여성,2025-01-05T01:07:47.000+09:00,NaN,True,0
115887,3791988,69632874,month,은은한덕수궁샌들,여행가서 잘입었어용 근데 많이 걸으니까 천에 쓸려서 살 다까짐 ㅠㅜ,4,False,S,166,60,여성,2025-01-05T01:07:47.000+09:00,NaN,True,0

In [22]:
reviews_all.info()

<class 'pandas.DataFrame'>
RangeIndex: 492504 entries, 0 to 492503
Data columns (total 15 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   goodsNo  492504 non-null  int64
 1   리뷰번호     492504 non-null  int64
 2   리뷰타입     492504 non-null  str
 3   작성자      492504 non-null  str
 4   리뷰내용     492282 non-null  str
 5   평점       492504 non-null  int64
 6   체험단      492504 non-null  bool
 7   구매옵션     492020 non-null  str
 8   키        492504 non-null  int64
 9   몸무게      492504 non-null  int64
 10  성별       403242 non-null  str
 11  작성일      492504 non-null  str
 12  만족도      17886 non-null   str
 13  사진유무     492504 non-null  bool
 14  도움돼요     492504 non-null  int64
dtypes: bool(2), int64(6), str(7)
memory usage: 133.8 MB