In [1]:
import pandas as pd

# CSV 파일 불러오기
df_reviews = pd.read_csv("reviews_002.csv")
df_products = pd.read_csv("products_002.csv")

In [2]:
display(df_reviews.info())
display(df_products.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14562 entries, 0 to 14561
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   goodsNo  14562 non-null  int64
 1   리뷰번호     14562 non-null  int64
 2   작성자      14562 non-null  object
 3   리뷰내용     14559 non-null  object
 4   평점       14562 non-null  int64
 5   체험단      14562 non-null  bool
 6   구매옵션     14554 non-null  object
 7   키        14562 non-null  int64
 8   몸무게      14562 non-null  int64
 9   성별       13945 non-null  object
 10  작성일      14562 non-null  object
 11  만족도      2393 non-null   object
 12  사진유무     14562 non-null  bool
 13  도움돼요     14562 non-null  int64
dtypes: bool(2), int64(6), object(6)
memory usage: 1.4+ MB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 12 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   플랫폼      80 non-null     object
 1   카테고리     80 non-null     object
 2   브랜드      80 non-null     object
 3   goodsNo  80 non-null     int64
 4   상품명      80 non-null     object
 5   정가       80 non-null     int64
 6   판매가      80 non-null     int64
 7   할인율(%)   80 non-null     int64
 8   조회수      80 non-null     int64
 9   누적판매수    80 non-null     int64
 10  리뷰수      80 non-null     int64
 11  리뷰점수     80 non-null     int64
dtypes: int64(8), object(4)
memory usage: 7.6+ KB

None

# Reviews 뜯어보기

In [35]:
# goodsNo
df_reviews['goodsNo'].nunique()

72

In [ ]:
# 리뷰번호
# 리뷰번호는 고유한 값일까?
print(f"고유한 리뷰번호 개수 : {df_reviews['리뷰번호'].nunique()}")
print(f"전체 행 개수 : {len(df_reviews)}")

# 리뷰번호는 고유한 값이 맞는듯!

고유한 리뷰번호 개수 : 14562
전체 행 개수 : 14562

In [ ]:
# 작성자
# 작성자명은 한글, 영어, 숫자를 제외하고 어떤 특수문자가 있을까?
import re

special_chars = df_reviews['작성자'].str.extractall(r'([^가-힣a-zA-Z0-9])')[0].unique()
print(special_chars)

['-' '~' '°' '_' '!' 'ㅎ' ' ' '.' 'ㅈ' 'ㅁ' 'ㅑ' '#' '@' '♫' 'ㄷ' 'ㄱ' 'ㅇ' 'ㄴ'
 'ㅋ' 'ㅣ' '^' ';' '\u200b' '’' '\u2007' 'ب' ':' 'ㅓ' 'డ' 'い' 'え' 'ㅜ' ',' 'ㅡ'
 '?' '|' '•' 'ㄹ' '✌' '︎' '`' 'ㅏ' '\u200d' 'ㅗ' 'ㅠ' 'ㄲ' '—' '夜' '櫻' '念' '⍤'
 '⃝' 'ㅂ' 'ㅚ' 'ル' 'フ' 'ィ' 'ㅔ' 'ㅢ' '٩' '๑' '❛' 'ᴗ' '۶' '♪' 'ㅕ' 'ㅐ' '樂' '左'
 '右' '盲' '⁍' '̴' '̆' 'Ɛ' '\u3000' '♥' '…' '♡' '*' 'ス' 'ン' 'ド' 'リ' 'ㅆ' '$'
 '⚓' '️' 'ღ' '心' 'を' '燃' 'や' 'せ' '。' '=' 'き' '¿' 'あ' 'み' 'ょ' 'ん' '+' 'ℒ'
 'ᵒ' 'ᵛ' 'ᵉ' 'ᵧ' 'ₒ' 'ᵤ' '安' '食' 'é' 'ギ' 'ョ' 'ㅊ']

In [ ]:
# 리뷰내용
# 리뷰내용은 한글, 영어, 숫자를 제외하고 어떤 특수문자가 있을까?
special_chars_review = df_reviews['리뷰내용'].str.extractall(r'([^가-힣a-zA-Z0-9])')[0].unique()
print(special_chars_review)

# \n은 공백인건가 아니면 진짜 \n으로 표현되는건가? => csv 파일에서는 \n이 실제 줄바꿈으로 표현되어 있음, 다만 데이터프레임에서는 \n으로 표현됨
display(df_reviews[df_reviews['리뷰내용'].str.contains(r'\n', na=False)])

#'\u202a', '\u200d', '\u200b' ?
display(df_reviews[df_reviews['리뷰내용'].str.contains(r'\u202a|\u200d|\u200b', na=False)])
# \u202a : Left-to-Right Embedding텍스트 방향을 왼→오른쪽으로 강제하는 제어문자
# \u200d : Zero Width Joiner이모지 조합 등에 쓰이는 폭 없는 문자
# \u200b : Zero Width Space폭 없는 공백 (줄바꿈 힌트용)
# 모두 눈에 보이지 않는 유니코드 제어문자로, 주로 모바일 앱이나 복사-붙여넣기 과정에서 섞여 들어옵니다.

[' ' '♡' '_' '~' '.' '\n' '!' '^' '(' ')' ';' ',' 'ㅎ' '-' 'ㅡ' 'ㅜ' '😍' 'ㅠ'
 'ㅋ' '?' 'ㄹ' 'ㅇ' '❤' '️' 'ㅖ' 'ㅣ' '👍' '…' 'ㅛ' 'ㅔ' 'ㄱ' 'ㅊ' 'ㅏ' 'ㄴ' ':' 'ㅈ'
 '@' '/' '👏' '🏻' '•' '💗' 'ㆅ' '🤙' '#' 'ㆍ' '🤍' 'ㅁ' 'ᐟ' '🔆' '😘' '&' 'ᆢ' 'ㄷ'
 '⌒' '🏿' '➰' '🤔' '%' '🥹' '😎' '😿' '😥' 'ㅆ' '🥺' '😝' '～' '๑' '･' '̑' '◡' 'ㅗ'
 '+' '✨' '💕' '😻' '😚' '🖤' 'ㅓ' 'ö' 'ㅂ' '‘' '😊' '✌' 'ᵔ' 'ᴥ' '🧚' '\u200d' '♀'
 '💛' '♥' '=' '⭐' '>' '<' '🤗' 'ㅕ' '🫶' '🤟' '🙂' '↕' '🩷' '🔥' 'ㅌ' '¡' '🤩' '☺'
 'ჱ' '̒' '⸝' '̀' '֊' '́' '\u202a' '😳' '😄' '̆' '̈' '*' '·' '●' '《' '》' '🏼'
 '🤭' '😁' '🧡' '😌' 'ʕ' '͡' 'ˑ' 'ཻ' 'ʔ' 'ㅃ' '🤞' 'ღ' 'ᴗ' '😆' '🥇' '🥈' '🥉' '🏆'
 '🥁' '[' ']' '✰' '💥' '🩶' '‼' '❣' 'ㅐ' 'ㅝ' 'ᶿ' '̴' '͈' '᷇' '̮' '˂' '᷆' '🫧'
 '💫' '“' '"' '🤤' '🤮' '̎' '😃' '😢' 'ㅑ' '😅' '⁽' '̨' '̡' 'ﻌ' '⁾' '̧' '̢' 'ɞ'
 '̶' '̷' '꒱' '😋' '꙼' '🙏' '😉' '✔' 'ｓ' '🌟' '💪' '✩' '🥰' '—' '★' '🥳' '😀' '🙄'
 '🙃' '₩' '👋' '🥕' '🍊' '☆' 'ᩚ' '🍯' 'ર' 'લ' 'ો' '👽' '🔍' '🎨' '💎' 'ㅟ' '💦' '⌯'
 '˃' 'ᵕ' 'ಣ' '︎' '🥲' '🩵' '！' '\u200b' '💖' '🍀' '🎄' '👌' '❗' "'" '”' '🌳' '💟'
 '👉' '👈' '🍂' '😂' '👀' '❄']

,goodsNo,리뷰번호,작성자,리뷰내용,평점,체험단,구매옵션,키,몸무게,성별,작성일,만족도,사진유무,도움돼요
6,2712417,83479496,꽃빛이어라,필루미네이트 사랑함..♡\n그냥 암때나 척척 걸쳐도\n핏이 넘 예픔!!!! \n휘뚜...,5,False,S,167,57,여성,2026-04-06T10:33:00.000+09:00,사이즈: 정사이즈 / 화면 대비 색감: 화면과 비슷 / 두께감: 적당함 / 퀄리티:...,True,2
9,2712417,83404688,꽃빛이어라,블랙 M 구입하고 좀 큰거같아서\n그레이는 S로 구입해봤어요~!\n소재며 핏이며 넘...,5,False,S,167,57,여성,2026-04-02T22:47:09.000+09:00,사이즈: 정사이즈 / 화면 대비 색감: 화면과 비슷 / 두께감: 적당함 / 퀄리티: 좋음,True,4
12,2712417,83283927,용감한이대빈티지,제질도 좋고 핏도 이뻐요\n교환처리할때 늦어져서 아쉽긴했지만 그래도 옷은 이뻐서 다...,5,False,S,170,65,남성,2026-03-28T20:39:24.000+09:00,사이즈: 정사이즈 / 화면 대비 색감: 화면과 비슷 / 두께감: 적당함 / 퀄리티:...,False,0
19,2712417,83096453,선한청계천웨지,무난하게 입기 딱 좋은 것 같아요\n색상도 화면 그대로이고 핏도 괜탆앙ㅎ,5,False,S,160,52,여성,2026-03-20T15:05:50.000+09:00,사이즈: 정사이즈 / 화면 대비 색감: 화면과 비슷 / 두께감: 적당함 / 퀄리티: 보통,False,0
24,2712417,82949739,아이리쉬밤밤,학교갈때 교복처럼 입고 다녔는데 좀 낡아서 새로 또 샀어요\n원단도 좋고 마감 지퍼...,5,False,XL,168,68,여성,2026-03-14T17:29:57.000+09:00,사이즈: 조금 큼 / 화면 대비 색감: 화면과 비슷 / 두께감: 적당함 / 퀄리티:...,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14550,5374745,79379288,웅장한삿포로퍼,따뜻하고 좋아여\n모자가 생각보다 작더라고욯\n지퍼가 살짝 끼긴 하는데 그거 빼곤 ...,5,False,S,157,48,여성,2025-10-27T22:57:02.000+09:00,NaN,False,0
14555,5374745,79167153,나리현,세탁해도 털이 잘 묻어나요\n안에 검은옷 입거나 하의 검은거 입으면 보송보송한 회색...,3,False,L,162,50,여성,2025-10-20T10:07:18.000+09:00,NaN,False,0
14556,5374745,79125493,풍성한뉴욕힐,일단 색이 너무 예뻐요! 일반 그레이가 아니라 더 밝은 느낌??\n핏도 완죤 좋구요...,5,True,M,173,68,남성,2025-10-18T18:22:43.000+09:00,NaN,True,0
14557,5374745,78735859,taeyyy,얇고 가볍고 따뜻할 것 같음 그리고 밑단 스프링 없는데 쪼여서 말려올라가요\n귀찮아...,5,False,S,157,50,여성,2025-10-03T13:53:37.000+09:00,NaN,True,10
14559,4728678,83697351,ㅊㄱㅎㅂ,무난초 바막 찾다 샀는데 개굳\n기대 별로 안 했는데 예쁨\n사이즈도 딱 괜찮고 휘...,5,False,S,158,53,여성,2026-04-15T13:04:58.000+09:00,사이즈: 정사이즈 / 화면 대비 색감: 화면과 비슷 / 퀄리티: 보통 / 두께감: 두꺼움,True,0

,goodsNo,리뷰번호,작성자,리뷰내용,평점,체험단,구매옵션,키,몸무게,성별,작성일,만족도,사진유무,도움돼요
3569,3455892,73492786,꿈많은남색민소매,하 너무 예쁘고 마음에 듦 처음에 너무 커서 당황했는데 스트링 조이니까 넘 굳임🧚‍♀️,5,False,S,157,39,여성,2025-04-24T20:02:38.000+09:00,NaN,True,3
3827,3455892,67730470,적립금주숑,간절기때 필수템이였던 옷 ..🙂‍↕️ \n특히 비올 때 손이 자주 가서 잘 입어줬어...,5,False,M,163,52,여성,2024-11-28T18:14:40.000+09:00,NaN,True,1
4460,3455892,58006412,무신시악개,지금 날씨에 딱이고 비오는날 방수 대박입니다 ჱ̒⸝⸝&bull;̀֊&bull;́⸝...,5,False,L,165,30,여성,2024-04-15T19:59:50.000+09:00,NaN,True,0
5168,3455882,77627897,안녕하삼요잉,입었을 때 편안함과 힙함이 동시에🤭❤️‍🔥\n날이 조금 더 선선해지면 자주 찾게 될...,5,False,M,163,48,여성,2025-08-14T00:55:47.000+09:00,NaN,True,0
9974,3616470,69802685,타코24,보온성 엄청 좋구요\n디자인이 엄청 깔끔해서 자주 입을 것 같아요\n믿고 사는 필루...,5,False,M,182,68,남성,2025-01-09T15:04:36.000+09:00,NaN,True,0
13816,5458312,79504757,모호한라임하객룩,FILLUMINATE에서 구매한 블랙 유광 패딩을 받았는데요. 배송은 압축된 비닐 ...,5,True,S,170,50,남성,2025-11-01T13:20:22.000+09:00,NaN,True,1
14510,5374745,82336657,우수한판교치마,​평소 입기 좋은 베이직한 디자인이라 대만족입니다! 원단이 탄탄해서 세탁 후에도 변...,5,False,M,174,73,남성,2026-02-18T16:55:05.000+09:00,사이즈: 정사이즈 / 화면 대비 색감: 화면과 비슷 / 퀄리티: 보통 / 두께감: 적당함,True,0

In [73]:
# 평점
# 평점 분포 확인하기

print(f"평점 분포:\n{df_reviews['평점'].value_counts(dropna=False)}")
# 평점
# 5    12076
# 4     1843
# 3      419
# 2       84
# 0       71
# 1       69

# 0점 평점 행 확인하기
print(f"\n0점 평점 행 개수: {df_reviews[df_reviews['평점'] == 0].shape[0]}")
# 평점이 0점이면 사진유무가 전부 True? => Yes
print(f"\n평점이 0점인 행의 사진유무 분포:\n{df_reviews[df_reviews['평점'] == 0]['사진유무'].value_counts(dropna=False)}") # True    71

# 그럼 사진유무가 전부 True이면 평점이 전부 0점일까? => No
print(f"\n그럼 사진유무가 전부 True이면 평점이 전부 0점일까?\n {df_reviews[df_reviews['사진유무'] == True]['평점'].value_counts(dropna=False)}")
# 평점
# 5    4934
# 4     767
# 3     152
# 0      71
# 1      21
# 2      19

평점 분포:
평점
5    12076
4     1843
3      419
2       84
0       71
1       69
Name: count, dtype: int64

0점 평점 행 개수: 71

평점이 0점인 행의 사진유무 분포:
사진유무
True    71
Name: count, dtype: int64

그럼 사진유무가 전부 True이면 평점이 전부 0점일까?
 평점
5    4934
4     767
3     152
0      71
1      21
2      19
Name: count, dtype: int64

In [67]:
# 체험단
print(df_reviews['체험단'].value_counts(dropna=False))
# False    14489
# True        73

# 체험단이 True인 행의 goodsNo 분포는 어떨까?
print(f"\n체험단이 True인 행의 goodsNo별 행 개수\n{df_reviews[df_reviews['체험단'] == True]['goodsNo'].value_counts(dropna=False)}")
print(f"체험단이 True인 행의 총 개수: {df_reviews[df_reviews['체험단'] == True]['goodsNo'].value_counts(dropna=False).sum()}")
# goodsNo
# 3455882    15
# 5900206    11
# 5797709    10
# 5900205     8
# 5458457     5
# 5458505     5
# 5458312     4
# 5923266     4
# 5900201     4
# 5374745     3
# 5374750     2
# 5333979     2

# 체험단이 True인 행의 goodsNo별 행 개수
target_goods = [3455882, 5900206, 5797709, 5900205, 5458457, 5458505, 5458312, 5923266, 5900201, 5374745, 5374750, 5333979]
print(f"\n체험단이 True인 행의 goodsNo별 행 개수\n{df_reviews[df_reviews['goodsNo'].isin(target_goods)]['goodsNo'].value_counts(dropna=False)}")

체험단
False    14489
True        73
Name: count, dtype: int64

체험단이 True인 행의 goodsNo별 행 개수
goodsNo
3455882    15
5900206    11
5797709    10
5900205     8
5458457     5
5458505     5
5458312     4
5923266     4
5900201     4
5374745     3
5374750     2
5333979     2
Name: count, dtype: int64
체험단이 True인 행의 총 개수: 73

체험단이 True인 행의 goodsNo별 행 개수
goodsNo
3455882    1774
5458457     287
5458505     229
5374750      77
5374745      68
5458312      61
5797709      20
5900206      18
5333979      11
5900205       9
5923266       9
5900201       8
Name: count, dtype: int64

In [74]:
# 구매옵션
df_reviews['구매옵션'].value_counts()

구매옵션
M                   5388
L                   4011
XL                  1835
S                   1459
M(논기모)               340
L(논기모)               304
XL(논기모)              223
XL(기모)               148
블랙 · M               147
블랙 · L               141
L(기모)                134
M(기모)                104
그레이 · L               65
블랙 · S                44
그레이 · M               32
챠콜 · M                29
챠콜 · L                25
BLACK / L             19
그레이 · S               18
BLACK / S             16
BLACK / M             16
챠콜 · S                15
CHARCOAL · M           8
LIGHT BLUE / M         7
BLACK · L              5
LIGHT BLUE / L         4
CHARCOAL · L           4
MELANGE GREY · M       3
F                      3
MELANGE GREY · L       2
LIGHT BLUE / S         1
GREY / L               1
BLACK · M              1
SKY BLUE · S           1
SKY BLUE · L           1
Name: count, dtype: int64

In [82]:
# 키
print(f"키 분포:\n{df_reviews['키'].value_counts(dropna=False)}")

# 키가 100미만이거나 200초과인 행 확인하기
height = df_reviews[(df_reviews['키'] < 100) | (df_reviews['키'] > 200)]
print(f"\n키가 100미만이거나 200초과인 행의 키 분포:\n{height['키'].value_counts(dropna=False)}")

키 분포:
키
170    1043
175     875
0       824
180     747
178     701
       ...
125       1
129       1
95        1
117       1
123       1
Name: count, Length: 61, dtype: int64

키가 100미만이거나 200초과인 행의 키 분포:
키
0      824
220      5
40       4
55       1
95       1
Name: count, dtype: int64

In [86]:
# 몸무게
print(f"몸무게 분포:\n{df_reviews['몸무게'].value_counts(dropna=False)}")

# 몸무게가 30미만이거나 200초과인 행 확인하기
weight = df_reviews[(df_reviews['몸무게'] < 30) | (df_reviews['몸무게'] > 200)]
print(f"\n몸무게가 30미만이거나 200초과인 행의 몸무게 분포:\n{weight['몸무게'].value_counts(dropna=False)}")

몸무게 분포:
몸무게
70     916
0      859
60     790
75     652
65     650
      ...
15       1
6        1
22       1
554      1
17       1
Name: count, Length: 102, dtype: int64

몸무게가 30미만이거나 200초과인 행의 몸무게 분포:
몸무게
0      859
2       28
10       6
3        4
5        4
12       2
6        1
554      1
8        1
22       1
15       1
558      1
14       1
17       1
Name: count, dtype: int64

In [87]:
# 성별
print(f"성별 분포:\n{df_reviews['성별'].value_counts(dropna=False)}")

성별 분포:
성별
남성     9016
여성     4929
NaN     617
Name: count, dtype: int64

In [ ]:
# 작성일
print(df_reviews['작성일'].value_counts())

print(f"\n최대 작성일: {df_reviews['작성일'].max()}")
print(f"최소 작성일: {df_reviews['작성일'].min()}")

작성일
2025-06-29T18:58:50.000+09:00    2
2025-09-28T18:27:30.000+09:00    2
2026-04-12T10:02:57.000+09:00    1
2025-03-08T15:54:22.000+09:00    1
2025-03-11T15:35:31.000+09:00    1
                                ..
2023-10-16T00:09:04.000+09:00    1
2023-10-16T00:08:01.000+09:00    1
2023-10-15T12:05:09.000+09:00    1
2023-10-15T12:04:52.000+09:00    1
2026-04-15T20:06:09.000+09:00    1
Name: count, Length: 14560, dtype: int64

최대 작성일: 2026-04-15T20:54:30.000+09:00
최소 작성일: 2022-09-02T21:01:28.000+09:00

In [97]:
# 만족도
#  만족도 열을 ' / '로 분리하여 딕셔너리 형태로 변환하는 함수 정의
def split_satisfaction(text):
    if pd.isna(text) or str(text).strip() == "":
        return {}
    parsed_dict = {}
    parts = str(text).split(' / ')
    for part in parts:
        if ': ' in part:
            key, value = part.split(': ', 1)
            parsed_dict[key.strip()] = value.strip()
    return parsed_dict

satisfaction_expanded = df_reviews['만족도'].apply(split_satisfaction).apply(pd.Series)
df_reviews_analysis = pd.concat([df_reviews, satisfaction_expanded], axis=1)

display(df_reviews_analysis.head())

review_list = ['사이즈','화면 대비 색감', '두께감', '퀄리티', '보온성']

for review in review_list:
    if review in df_reviews_analysis.columns:
        counts = df_reviews_analysis[review].value_counts(dropna=False)
        ratios = df_reviews_analysis[review].value_counts(normalize=True, dropna=False) * 100
        
        result_df = pd.DataFrame({
            '개수': counts,
            '비율(%)': ratios.round(2) # 소수점 둘째 자리까지 반올림
        })
        
        print(f"\n========== [ {review} ] ==========")
        print(result_df)

,goodsNo,리뷰번호,작성자,리뷰내용,평점,체험단,구매옵션,키,몸무게,성별,작성일,만족도,사진유무,도움돼요,사이즈,화면 대비 색감,두께감,퀄리티,보온성
0,2712417,83619497,스윗한프라하향수,가볍게 입을 수 있고 편안하게 입을 후드 집업이 필요 했는데 딱 사서 좋았어용♡_♡,5,False,S,163,50,여성,2026-04-12T10:02:57.000+09:00,사이즈: 정사이즈 / 화면 대비 색감: 화면과 비슷 / 두께감: 적당함 / 퀄리티: 보통,False,0,정사이즈,화면과 비슷,적당함,보통,NaN
1,2712417,83614437,심플한연두색셔링,첨 사봤지만 사이즈 색상 두께 다맘에듭니다 괜춘괜춘,5,False,XL,180,90,남성,2026-04-11T23:19:35.000+09:00,사이즈: 정사이즈 / 화면 대비 색감: 화면과 비슷 / 두께감: 적당함 / 퀄리티: 보통,False,0,정사이즈,화면과 비슷,적당함,보통,NaN
2,2712417,83607439,20-J180,깔끔하고 이쁩니다 봄이입기좋아요 디테일도 좋아요,3,False,M,168,59,남성,2026-04-11T18:17:30.000+09:00,사이즈: 정사이즈 / 화면 대비 색감: 화면과 비슷 / 두께감: 적당함 / 퀄리티: 보통,True,0,정사이즈,화면과 비슷,적당함,보통,NaN
3,2712417,83607433,20-J180,싼고 이뻐요~ 딱 평범함 회색후드집업입니다. 봄에 입기좋아요,5,False,M,168,59,남성,2026-04-11T18:17:03.000+09:00,사이즈: 정사이즈 / 화면 대비 색감: 화면과 비슷 / 두께감: 적당함 / 퀄리티: 보통,True,0,정사이즈,화면과 비슷,적당함,보통,NaN
4,2712417,83562279,국수매니아,받자마자 거의 매일 입고 있어요 루즈핏인데 편해요,5,False,M,160,60,여성,2026-04-09T18:19:46.000+09:00,사이즈: 조금 큼 / 화면 대비 색감: 화면과 비슷 / 두께감: 적당함 / 퀄리티: 좋음,False,0,조금 큼,화면과 비슷,적당함,좋음,NaN

========== [ 사이즈 ] ==========
          개수  비율(%)
사이즈
NaN    12169  83.57
정사이즈    1426   9.79
조금 큼     725   4.98
많이 큼     164   1.13
조금 작음     55   0.38
매우 작음     23   0.16

========== [ 화면 대비 색감 ] ==========
             개수  비율(%)
화면 대비 색감
NaN       12169  83.57
화면과 비슷     2053  14.10
어두움         137   0.94
밝음          128   0.88
매우 어두움       42   0.29
매우 밝음        33   0.23

========== [ 두께감 ] ==========
           개수  비율(%)
두께감
NaN     13513  92.80
적당함       688   4.72
얇음        228   1.57
두꺼움        70   0.48
매우 얇음      49   0.34
매우 두꺼움     14   0.10

========== [ 퀄리티 ] ==========
          개수  비율(%)
퀄리티
NaN    12176  83.61
보통      1280   8.79
좋음       525   3.61
매우 좋음    450   3.09
나쁨       100   0.69
매우 나쁨     31   0.21

========== [ 보온성 ] ==========
          개수  비율(%)
보온성
NaN    13239  90.91
적당함      563   3.87
좋음       419   2.88
매우 좋음    277   1.90
거의 없음     47   0.32
전혀 없음     17   0.12

In [103]:
# 만족도에서 Nan인 케이스 비교

cols = ['사이즈', '화면 대비 색감', '두께감', '퀄리티', '보온성']

df_reviews_analysis.groupby(
    [df_reviews_analysis[col].notna().rename(col) for col in cols]
).size().reset_index(name='행 개수')

     사이즈  화면 대비 색감    두께감    퀄리티    보온성   행 개수
0  False     False  False  False  False  12169
1   True      True  False  False  False      7
2   True      True  False   True  False     14
3   True      True  False   True   True   1323
4   True      True   True   True  False   1049

In [104]:
# 사진유무
print(f"사진유무 분포:\n{df_reviews['사진유무'].value_counts(dropna=False)}")

사진유무 분포:
사진유무
False    8598
True     5964
Name: count, dtype: int64

In [105]:
# 도움돼요
print(f"도움돼요 분포:\n{df_reviews['도움돼요'].value_counts(dropna=False)}")

도움돼요 분포:
도움돼요
0     13277
1       755
2       213
3        96
4        49
5        30
6        21
9        15
8        12
7        12
11       10
10       10
12        8
19        6
15        5
18        5
17        4
24        4
13        3
22        3
30        3
20        2
16        2
27        2
48        1
37        1
49        1
21        1
32        1
29        1
55        1
44        1
33        1
28        1
40        1
54        1
76        1
25        1
42        1
Name: count, dtype: int64

In [124]:
# 전체 중복 => 0
print(f"전체 중복 개수: {df_reviews.duplicated().sum()}")   

# 리뷰내용 중복 확인
print(f"리뷰내용 중복 개수: {df_reviews['리뷰내용'].duplicated().sum()}")
df_reviews[df_reviews['리뷰내용'].duplicated(keep=False)].sort_values('리뷰내용')

전체 중복 개수: 0
리뷰내용 중복 개수: 1089

,goodsNo,리뷰번호,작성자,리뷰내용,평점,체험단,구매옵션,키,몸무게,성별,작성일,만족도,사진유무,도움돼요
8271,2712419,34730467,쭌매니저,\n색감 재질 핏 다 맘에 드네요 오버핏으로 여유잇음,5,False,XL,181,82,남성,2022-11-10T10:20:16.000+09:00,NaN,False,0
8272,2712419,34730458,쭌매니저,\n색감 재질 핏 다 맘에 드네요 오버핏으로 여유잇음,5,False,XL,181,82,남성,2022-11-10T10:20:01.000+09:00,NaN,True,1
6250,3455882,57769883,정따뚜이,포인트 주기 좋은 얇은 바람막이 입니다. \n 회끼 도는 민트색이 베이스에 그레이...,4,False,M,186,74,남성,2024-04-09T22:02:54.000+09:00,NaN,True,0
6249,3455882,57769957,정따뚜이,포인트 주기 좋은 얇은 바람막이 입니다. \n 회끼 도는 민트색이 베이스에 그레이...,4,False,M,186,74,남성,2024-04-09T22:04:39.000+09:00,NaN,True,0
6251,3455882,57769861,정따뚜이,포인트 주기 좋은 얇은 바람막이 입니다. \n 회끼 도는 민트색이 베이스에 그레이...,4,False,M,186,74,남성,2024-04-09T22:02:28.000+09:00,NaN,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2796,2712417,37544007,닉네임짜증낭,휘뚤마뚤 입기 조아요 크긴한데 투웨이라서 조아요 잎쪽은 어깨선있는데 뒤에가 레글런 ...,5,False,L,163,65,여성,2022-12-29T21:33:01.000+09:00,NaN,True,27
2795,2712417,37544019,닉네임짜증낭,휘뚤마뚤 입기 조아요 크긴한데 투웨이라서 조아요 잎쪽은 어깨선있는데 뒤에가 레글런 ...,5,False,L,163,65,여성,2022-12-29T21:33:16.000+09:00,NaN,False,0
1144,2712417,66149373,명확한대전긴팔티,NaN,0,False,M,160,65,여성,2024-10-06T15:56:10.000+09:00,NaN,True,0
4002,3455892,66081002,기발한피사망토,NaN,0,False,L,0,0,여성,2024-08-23T09:51:40.000+09:00,NaN,True,0
5781,3455882,66303366,hominguk,NaN,0,False,M,0,0,남성,2024-09-14T03:03:36.000+09:00,NaN,True,0